trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'mrs-backend-docker'
stages:
  - stage: Scan
    jobs:
      - job: Scan_Secrets
        displayName: Scan secrets
        steps:
          - checkout: self
            fetchDepth: -1
          - task: Gitleaks@3
            inputs:
              scanlocation: '$(Build.SourcesDirectory)'
              configtype: 'predefined'
              predefinedconfigfile: 'GitleaksUdmCombo.toml'
              reportformat: 'sarif'
  - stage: Build
    jobs:
      - job: Build_image
        displayName: Build image
        steps:
           - task: Docker@2
             displayName: Build an image
             inputs:
               repository: $(imageName)
               command: build
               Dockerfile: mrs-backend/Dockerfile
